### ISSUE TITLE
Error: ENOENT: no such file or directory, open '. /file.json'

### ISSUE THREAD

**Issue by micahblu** [sindresorhus/load-json-file#9]
It cannot seem to find the files which are there. I was able to require the file I needed as js with the same exact path save for the extension. To be sure the issue was not caused by a file path typo I did the following:

`echo "{}" > file.json`

Then in the importing file in the same directory:

```js
const loadJsonFile = require('load-json-file');
 
loadJsonFile('./file.json').then(json => {
    console.log(json);
    //=> {foo: true} 
});
```

which produced the error:
`Error: ENOENT: no such file or directory, open '. /file.json'`

**Comment by sindresorhus** [comment]
Make sure the `process.cwd()` (try logging it) is correct. `./file.json` is relative from where the Node.js process was started, not where the source file is.

**Comment by SamVerschueren** [comment]
If you want it relative to the source file, `path.join(__dirname, 'file.json')`

**Comment by micahblu** [comment]
Thank you both. That was the issue.

**Comment by Yatendrajain** [comment]
> If you want it relative to the source file, `path.join(__dirname, 'file.json')`

Thank you . I used path.resolve ! however it was working earlier and suddenly started raising error ! thank to you , You solved it

**Comment by akhseri97** [comment]
im getting this error when im running npm run serve:electron. help pls?

error while reading config.json:  Error: ENOENT: no such file or directory, stat '/data/config.json'
    at statSync (fs.js:856:3)
    at fs.statSync (electron/js2c/asar.js:276:27)
    at Object.fs.statSync (electron/js2c/asar.js:276:27)
    at getConfig (webpack:///./src/background.js?:23:47)
    at eval (webpack:///./src/background.js?:31:1)
    at Module../src/background.js (/Users/aijuldizbota/evm-charging-station/ui-service/client/dist_electron/index.js:1234:1)
    at __webpack_require__ (/Users/aijuldizbota/evm-charging-station/ui-service/client/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/Users/aijuldizbota/evm-charging-station/ui-service/client/dist_electron/index.js:1245:1)
    at __webpack_require__ (/Users/aijuldizbota/evm-charging-station/ui-service/client/dist_electron/index.js:20:30) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/data/config.json'
}
Running in development mode
Uncaught (in promise) Error: Invalid header: Does not start with Cr24
    at crxToZip (webpack:///./node_modules/unzip-crx/dist/index.js?:32:15)
    at eval (webpack:///./node_modules/unzip-crx/dist/index.js?:57:32)
    at callHanler (webpack:///./node_modules/yaku/lib/yaku.js?:719:16)
    at tryCatcher (webpack:///./node_modules/yaku/lib/yaku.js?:436:32)
    at eval (webpack:///./node_modules/yaku/lib/yaku.js?:575:38)
    at flush (webpack:///./node_modules/yaku/lib/yaku.js?:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by Amiin29** [comment]
![image](https://user-images.githubusercontent.com/67683686/113860942-8b24be00-979e-11eb-9990-583778b8b9ff.png)
help me please i have this issue

**Comment by Tirna-Misti-Roy** [comment]
hey, have you found the fix? 
I am facing the same issue

**Comment by vianodinapoli** [comment]
Também eu!

**Comment by Ozodbek-bakhtiyorov** [comment]
I have same problem

**Comment by andersonBrunu** [comment]
I SOLVE IT BY ADDING THE .JSON FILE IN THE ROOT FOLDER OF THE PROJECT AND PASSING THE PATH.JOIN(__DIRNAME, "FILE.JSON").
THIS IS FOR STUDY BUT I CANNOT SET THE FILE IN SOME OTHER FOLDER.

**Comment by labibahmed10** [comment]
@andersonBrunu hey I think I got a solve - 

First you try to console.log(process.csw()) and make sure where is your current directory is! then you can just go like (process.cwd() + "/directory/file.any") and then see the result. 

if you want to read the file as an example - 
const data = fs.readFileSync(process.cwd() + "/directory/file.any") and then parse it! 

I hope it will solve yours too as it solved mine.

**Comment by darwin-j** [comment]
Thanks @labibahmed10  it worked for me
